# server configuration
server: 
  port: 9001

# logging configuration
logger:
  # possible values: error, warn, info, debug, trace
  level: 'info' 

destination:
  loop: true
  sequence:
    - '5 00002,00003,00004'
    - '* 00012,00013,00014'
